name: Run periodically
run-name: HDS Analytics
on: 
  workflow_dispatch:
    # run on 1st day of every month at 00:00
  schedule:
    - cron: '0 0 1 * *'
jobs:
  Run-HDS-Analytics:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Read .nvmrc
        run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_OUTPUT
        id: nvmrc

      - name: setup node ${{ steps.nvmrc.outputs.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: '${{ steps.nvmrc.outputs.NODE_VERSION }}'
          registry-url: 'https://registry.npmjs.org'

      - name: install dependencies
        run: |
          yarn config set network-timeout 300000 
          yarn

      - name: run analytics
        run: |
          yarn start
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}

      # copy all files from tmp_results to results (and create results if it doesn't exist)
      - name: Copy results
        run: |
          mkdir -p results
          cp -r tmp_results/* results

      # commit changes to branch name "results"
      - name: Commit changes
        run: |
          git config --global user.email "hds@hel.fi"
          git config --global user.name "GitHub Actions"
          git remote add origin-https "https://github.com/City-of-Helsinki/hds-analytics.git"
          git fetch --all
          git add results/*
          git stash
          git checkout origin/results
          git stash pop
          git commit -m "Add results"
          git rebase origin/main
          git push --force origin HEAD:results
